//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGE
    {
        public string CODI_AGE { get; set; }
        public string CODI_SEC { get; set; }
        public string CODI_BAS { get; set; }
        public string CODI_ZON { get; set; }
        public string DES { get; set; }
        public string NOM { get; set; }
        public string NIF { get; set; }
        public string DIR { get; set; }
        public string POS { get; set; }
        public string POB { get; set; }
        public string PRV { get; set; }
        public string TEL_3 { get; set; }
        public string TEL_1 { get; set; }
        public string TEL_2 { get; set; }
        public string FAX { get; set; }
        public string OBS { get; set; }
        public decimal NUMERO { get; set; }
        public string E_MAIL { get; set; }
        public string CONTACTE { get; set; }
        public string E_MAIL_CONTACTE { get; set; }
        public string CARREC_CONTACTE { get; set; }
        public string WEB { get; set; }
        public string CODI_USU { get; set; }
        public string CODI_CAA { get; set; }
        public string CODI_SUA { get; set; }
        public decimal TERMINAL_SI_NO { get; set; }
    }
}
