//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALC_LIN
    {
        public string NUM_INTERN { get; set; }
        public string SYS_215 { get; set; }
        public string CODI_MAT { get; set; }
        public string DES { get; set; }
        public string CODI_MAG { get; set; }
        public decimal UNITATS { get; set; }
        public decimal PREU { get; set; }
        public decimal TANT_X100_DTE { get; set; }
        public decimal TANT_X100_IVA { get; set; }
        public decimal TOTAL { get; set; }
        public string COMENTARI { get; set; }
        public string NUM_OTR { get; set; }
        public string CODI_EMP { get; set; }
        public string CODI_VHI { get; set; }
        public string CODI_TRB { get; set; }
        public string TIPUS_ALC { get; set; }
        public string CODI_MAG_QUE_REP { get; set; }
        public Nullable<System.DateTime> DATA_CADUCITAT { get; set; }
        public decimal IGNORAR_ESTOC_SI_NO { get; set; }
        public string TIPUS_ORIGEN { get; set; }
        public string SERIE_NUM_ORIGEN { get; set; }
        public string NUM_LOT { get; set; }
    }
}
