//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUT
    {
        public string CODI_EMP { get; set; }
        public string CODI_EMP_FCT { get; set; }
        public string NUM_INTERN { get; set; }
        public string NUM_FCT { get; set; }
        public string CODI_LOT { get; set; }
        public Nullable<System.DateTime> DATA_EMISSIO { get; set; }
        public Nullable<System.DateTime> DATA_VTO { get; set; }
        public Nullable<System.DateTime> DATA_ALTA { get; set; }
        public string ESTAT { get; set; }
        public decimal IMP_SRV { get; set; }
        public decimal IMP_IVA { get; set; }
        public decimal IMP_TOTAL { get; set; }
        public decimal IMP_DTE { get; set; }
        public decimal IMP_BASE_IVA { get; set; }
        public decimal IMP_BASE_IVA_2 { get; set; }
        public decimal IMP_IVA_2 { get; set; }
        public decimal TANT_X100_DTE { get; set; }
        public string DES_BAN { get; set; }
        public string CC { get; set; }
        public string REFERENCIA { get; set; }
        public string OBS { get; set; }
        public string FORMA_PAGA { get; set; }
        public string SERIE { get; set; }
    }
}
