//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUT_LIN
    {
        public string CODI_EMP { get; set; }
        public string CODI_EMP_FCT { get; set; }
        public string DES_MET { get; set; }
        public string DES_ENF { get; set; }
        public string NUM_SRV { get; set; }
        public string CODI_LOT { get; set; }
        public Nullable<System.DateTime> DATA_INICI_SRV { get; set; }
        public string NOM { get; set; }
        public string COGNOMS { get; set; }
        public string CODI_MET { get; set; }
        public string CODI_ENF { get; set; }
        public decimal TOTAL { get; set; }
        public decimal PREU_INFERMERA { get; set; }
        public decimal PREU_METGE { get; set; }
        public string NUM_INTERN { get; set; }
        public string SYS_215 { get; set; }
    }
}
