//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVI
    {
        public string NUM_AVI { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<System.DateTime> DATA_VIST { get; set; }
        public string CODI_USU { get; set; }
        public decimal VIST_SI_NO { get; set; }
        public string OBS { get; set; }
        public string DOCUMENT { get; set; }
        public string USU_ENV { get; set; }
        public string DES { get; set; }
    }
}
