//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG
    {
        public string SYS_215 { get; set; }
        public string SQL_TERMINALS { get; set; }
        public string FIREBIRD_TERMINALS { get; set; }
        public string FIREBIRD_DATS { get; set; }
        public string DOMINIO { get; set; }
        public string CLAVE { get; set; }
        public string SRV_MOV { get; set; }
        public string USU_MOV { get; set; }
        public string PAS_MOV { get; set; }
        public decimal PORT_MOV { get; set; }
        public string URL_GOOGLEMAPS_XY { get; set; }
        public string IP_CENTRALETA { get; set; }
        public string CLIENT_ABBANZA { get; set; }
        public string PATHWEB_COORDINACIO { get; set; }
        public string PATHWEB_RRHH { get; set; }
        public string PATHWEB_TALLER { get; set; }
        public string PATHWEB_FACTURACIO { get; set; }
        public string PATHWEB_STOCK { get; set; }
        public string ALTURA_CELDA_ADJUDICATS { get; set; }
        public string ALTURA_CELDA_PENDENTS { get; set; }
        public string ALTURA_CELDA_MISSATGES { get; set; }
        public string ALTURA_CELDA_FINALITZATS { get; set; }
        public string REGISTRES_GRID_ADJUDICATS { get; set; }
        public string REGISTRES_GRID_PENDENTS { get; set; }
        public string REGISTRES_GRID_MISSATGES { get; set; }
        public string REGISTRES_GRID_FINALITZATS { get; set; }
        public string TAMANY_ADJUDICATS { get; set; }
        public string TAMANY_PENDENTS { get; set; }
        public string TAMANY_MISSATGES { get; set; }
        public string TAMANY_FINALITZATS { get; set; }
        public decimal CLIENT_OSOFT { get; set; }
        public decimal USU_CONNECTATS_GAMWEB { get; set; }
        public string USU_RCA { get; set; }
        public string PWD_RCA { get; set; }
        public decimal CALCULO_SRV { get; set; }
        public decimal ESTIJORES { get; set; }
        public decimal ESTIJORES_SI_NO { get; set; }
        public string PATH_DOC_EMAIL { get; set; }
        public int SRV_ENRUTADOS { get; set; }
        public int SRV_PROGRAMADOS_ENRUTABLES { get; set; }
        public int SRV_PROGRAMADOS_TOTALES { get; set; }
        public string PATH_DOC_SCANNER { get; set; }
        public decimal GAM_AUTOMATIC_SERGAS_SI_NO { get; set; }
        public string CONTROL_VERSION_GAMDROID { get; set; }
        public string CTRL_VERSION_GAMDROID { get; set; }
        public string PATH_DOC_SRV { get; set; }
        public string ACCOUNT_TOMTOM { get; set; }
        public string USERNAME_TOMTOM { get; set; }
        public string PASSWORD_TOMTOM { get; set; }
    }
}
