//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAC
    {
        public string SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string CATEGORIA { get; set; }
        public string CODI_VHI { get; set; }
        public string VEHICLE { get; set; }
        public string LLOC { get; set; }
        public string BASE { get; set; }
        public decimal ASSIGNAT_SI_NO { get; set; }
        public decimal INACTIU_SI_NO { get; set; }
        public string OBS { get; set; }
        public string CODI_CAT { get; set; }
        public string CODI_BAS { get; set; }
        public string SYS_215_QUA { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
    }
}
