//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT
    {
        public string CODI_EMP { get; set; }
        public decimal NUM_MISSATGE { get; set; }
        public string IO { get; set; }
        public string TIPUS_MISSATGE { get; set; }
        public string NUM_SRV { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<System.DateTime> DATA_MISSATGE { get; set; }
        public string NOM { get; set; }
        public string COGNOMS { get; set; }
        public string DIR_ORIGEN { get; set; }
        public string POB_ORIGEN { get; set; }
        public string DIR_DESTI { get; set; }
        public string POB_DESTI { get; set; }
        public string CODI_DIG { get; set; }
        public string CODI_TRA { get; set; }
        public string CODI_TRM { get; set; }
        public string P10 { get; set; }
        public string CLAU_MISSATGE { get; set; }
        public string TEXTCIP { get; set; }
        public string LLIURE { get; set; }
        public string ACCIONS_SRV { get; set; }
        public string CODI_XOF { get; set; }
        public string CODI_AJU { get; set; }
        public string CODI_VHI { get; set; }
        public decimal KM { get; set; }
        public decimal IMP { get; set; }
        public decimal LITRES { get; set; }
    }
}
