//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_SRV
    {
        public string SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA_VIST { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public decimal VIST_SI_NO { get; set; }
        public Nullable<System.DateTime> DATA_MISSATGE { get; set; }
        public string NUM_SRV { get; set; }
        public string P10 { get; set; }
        public decimal ACOMPANYAT { get; set; }
        public string CODI_TRA { get; set; }
        public decimal OXIGEN { get; set; }
        public decimal METGE { get; set; }
        public decimal ATS { get; set; }
        public string NOM { get; set; }
        public string ADRECA_INICI { get; set; }
        public string ADRECA_FINAL { get; set; }
        public string OBS { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public decimal LATITUD { get; set; }
        public decimal LONGITUT { get; set; }
        public string NASS { get; set; }
        public string TEL_SRV { get; set; }
    }
}
