//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_BUS
    {
        public int SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA_ARRIBADA { get; set; }
        public Nullable<System.DateTime> DATA_SORTIDA { get; set; }
        public decimal PARADA { get; set; }
        public string CODI_TRB { get; set; }
        public string CODI_VHI { get; set; }
        public decimal PACIENTS_PUJEN_CAMINANT { get; set; }
        public decimal PACIENTS_PUJEN_CADIRA_RODES { get; set; }
        public decimal PACIENTS_BAIXEN_CAMINANT { get; set; }
        public decimal PACIENTS_BAIXEN_CADIRA_RODES { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
    }
}
