//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_ATU
    {
        public string SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<System.DateTime> DATA_MISSATGE { get; set; }
        public string CODI_ATU { get; set; }
        public string INICI_FINAL { get; set; }
        public string CODI_VHI { get; set; }
        public string CODI_XOF { get; set; }
        public string CODI_AJU { get; set; }
        public string CODI_MET { get; set; }
        public string CODI_ATS { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public decimal LATITUD { get; set; }
        public decimal LONGITUT { get; set; }
    }
}
