//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DES
    {
        public string CODI_DES { get; set; }
        public string DES1 { get; set; }
        public string NOM_UNITATS { get; set; }
        public decimal KM_SI_NO { get; set; }
    }
}
