//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIA
    {
        public Nullable<System.DateTime> DATA { get; set; }
        public string DIA_SEMANA { get; set; }
        public decimal SRV_PRG { get; set; }
        public decimal SRV_NOR { get; set; }
        public decimal MAXIM_PRG { get; set; }
        public decimal MAXIM_NOR { get; set; }
        public string SYS_215 { get; set; }
        public string CODI_DIG { get; set; }
        public string CODI_PRC { get; set; }
    }
}
