//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIG
    {
        public string CODI_DIG { get; set; }
        public string DES { get; set; }
        public string OBS { get; set; }
        public decimal MARCAR_FESTIU_SI_NO { get; set; }
        public string DIG_EXTERN { get; set; }
        public decimal COLOR { get; set; }
    }
}
