//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIR
    {
        public string CODI_DIR { get; set; }
        public string DES { get; set; }
        public string POB { get; set; }
        public string POSICIO { get; set; }
        public string CODI_BAS { get; set; }
        public string CODI_SEC { get; set; }
        public string CODI_ZON { get; set; }
        public string OBS { get; set; }
        public string CODI_UP { get; set; }
        public string PROCEDENCIA { get; set; }
        public string CODI_PRC { get; set; }
        public string DIA_MES_FESTIU { get; set; }
        public string TEL { get; set; }
        public string CP { get; set; }
        public string DIA_MES_FESTIU_1 { get; set; }
        public string DIA_MES_FESTIU_2 { get; set; }
        public string DIR_EXTERNA { get; set; }
        public string DES_REDUIT { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public decimal LATITUD { get; set; }
        public decimal LONGITUD { get; set; }
        public string DOM { get; set; }
        public decimal PRIORITAT { get; set; }
        public decimal MINUTS_EN_RECOLLIR { get; set; }
        public decimal MINUTS_EN_DEIXAR { get; set; }
        public string PRV { get; set; }
        public decimal INACTIU_SI_NO { get; set; }
    }
}
