//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIR_EXTERN
    {
        public string SYS_215 { get; set; }
        public string ENTITAT { get; set; }
        public string CODI_DIR_GAM { get; set; }
        public string CODI_DIR_EXTERN { get; set; }
        public string DES_EXTERN { get; set; }
    }
}
