//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIS
    {
        public string SYS_215 { get; set; }
        public string DES { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string MARCA { get; set; }
        public string MODEL { get; set; }
        public string UBICACIO { get; set; }
        public string FABRICANT { get; set; }
        public string NUMERO_SERIE { get; set; }
        public Nullable<System.DateTime> DATA_GARANTIA { get; set; }
        public string ESTAT { get; set; }
        public string CODI_PRO { get; set; }
        public string CODI_VHI { get; set; }
        public string CODI_TRB { get; set; }
        public Nullable<decimal> PREU { get; set; }
        public string OBS { get; set; }
        public string TIPUS_DIS { get; set; }
    }
}
