//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DST
    {
        public string CODI_DST { get; set; }
        public string DES { get; set; }
        public decimal KMSS { get; set; }
        public decimal KMPRV { get; set; }
        public decimal KMCOL { get; set; }
        public decimal TEMPS_PREVIST { get; set; }
        public string POB_1 { get; set; }
        public string POB_2 { get; set; }
        public string CODI_ZON { get; set; }
        public string CODI_BAS { get; set; }
        public string CODI_SEC { get; set; }
        public decimal IMP_DESTI { get; set; }
        public decimal TANT_X100_DESTI { get; set; }
    }
}
