//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP
    {
        public string CODI_EMP { get; set; }
        public string DES { get; set; }
        public string DOM_1 { get; set; }
        public string DOM_2 { get; set; }
        public string WEB { get; set; }
        public string E_MAIL { get; set; }
        public string FAX { get; set; }
        public string NIF { get; set; }
        public string TEL { get; set; }
        public string OBS { get; set; }
        public string PAI { get; set; }
        public string POB { get; set; }
        public string POS { get; set; }
        public string PRV { get; set; }
        public string LOGO { get; set; }
        public string LLOC_EMISSIO { get; set; }
        public string TAULES_AUX { get; set; }
        public string TAULES_MES { get; set; }
        public decimal SISTEMA_SI_NO { get; set; }
        public string SITUACIO_1 { get; set; }
        public string SITUACIO_2 { get; set; }
        public string SITUACIO_3 { get; set; }
        public string SITUACIO_4 { get; set; }
        public string SITUACIO_5 { get; set; }
        public string POB_CARTOGRAFIA { get; set; }
        public string PRV_CARTOGRAFIA { get; set; }
        public string CAMP_1 { get; set; }
        public string CAMP_2 { get; set; }
        public string CAMP_3 { get; set; }
        public string CAMP_4 { get; set; }
        public string CAMP_5 { get; set; }
        public string CAMP_6 { get; set; }
        public string CAMP_7 { get; set; }
        public string CAMP_8 { get; set; }
        public string CAMP_9 { get; set; }
        public string CAMP_10 { get; set; }
        public decimal CAMP_11 { get; set; }
        public decimal CAMP_12 { get; set; }
        public decimal CAMP_13 { get; set; }
        public decimal CAMP_14 { get; set; }
        public decimal CAMP_15 { get; set; }
        public decimal CAMP_16 { get; set; }
        public decimal CAMP_17 { get; set; }
        public decimal CAMP_18 { get; set; }
        public decimal CAMP_19 { get; set; }
        public decimal CAMP_20 { get; set; }
        public decimal SI_NO_1 { get; set; }
        public decimal SI_NO_2 { get; set; }
        public decimal SI_NO_3 { get; set; }
        public decimal SI_NO_4 { get; set; }
        public decimal SI_NO_5 { get; set; }
        public decimal SI_NO_6 { get; set; }
        public decimal SI_NO_7 { get; set; }
        public decimal SI_NO_8 { get; set; }
        public decimal SI_NO_9 { get; set; }
        public decimal SI_NO_10 { get; set; }
        public decimal SI_NO_11 { get; set; }
        public decimal SI_NO_12 { get; set; }
        public decimal SI_NO_13 { get; set; }
        public decimal SI_NO_14 { get; set; }
        public decimal SI_NO_15 { get; set; }
        public decimal SI_NO_16 { get; set; }
        public decimal SI_NO_17 { get; set; }
        public decimal SI_NO_18 { get; set; }
        public decimal SI_NO_19 { get; set; }
        public decimal SI_NO_20 { get; set; }
        public string PATH_COMPTABILITAT { get; set; }
        public string CTA_IVA { get; set; }
        public string CTA_BAN { get; set; }
        public string CTA_ING { get; set; }
        public decimal SI_NO_21 { get; set; }
        public decimal SI_NO_22 { get; set; }
        public decimal SI_NO_23 { get; set; }
        public decimal SI_NO_24 { get; set; }
        public decimal SI_NO_25 { get; set; }
        public decimal SI_NO_26 { get; set; }
        public decimal SI_NO_27 { get; set; }
        public decimal SI_NO_28 { get; set; }
        public decimal SI_NO_29 { get; set; }
        public decimal SI_NO_30 { get; set; }
        public string INSTRUCCIO { get; set; }
        public string E_MAIL_JMAIL { get; set; }
        public string PWD_JMAIL { get; set; }
        public string SMTP_JMAIL { get; set; }
        public decimal SI_NO_31 { get; set; }
        public decimal SI_NO_32 { get; set; }
        public decimal SI_NO_33 { get; set; }
        public decimal SI_NO_34 { get; set; }
        public decimal SI_NO_35 { get; set; }
        public decimal SI_NO_36 { get; set; }
        public decimal SI_NO_37 { get; set; }
        public decimal SI_NO_38 { get; set; }
        public decimal SI_NO_39 { get; set; }
        public decimal SI_NO_40 { get; set; }
        public string RESPONSABLE_1 { get; set; }
        public string RESPONSABLE_2 { get; set; }
        public string RESPONSABLE_3 { get; set; }
        public string RESPONSABLE_4 { get; set; }
        public decimal SI_NO_41 { get; set; }
        public decimal SI_NO_42 { get; set; }
        public decimal SI_NO_43 { get; set; }
        public decimal SI_NO_44 { get; set; }
        public string PWD { get; set; }
        public decimal SI_NO_45 { get; set; }
        public decimal TRNUX_SI_NO { get; set; }
        public string POP3_JMAIL { get; set; }
        public string HORA_INICI { get; set; }
        public string HORA_FINAL { get; set; }
        public decimal HORARI_NOCTURN_SI_NO { get; set; }
        public decimal SI_NO_46 { get; set; }
        public decimal EMP_P_SI_NO { get; set; }
        public string E_MAIL_JMAIL_FROM { get; set; }
        public decimal SI_NO_47 { get; set; }
        public decimal SI_NO_48 { get; set; }
        public decimal SI_NO_49 { get; set; }
        public decimal SI_NO_50 { get; set; }
        public decimal SI_NO_51 { get; set; }
        public decimal SI_NO_52 { get; set; }
        public decimal SI_NO_53 { get; set; }
        public decimal SI_NO_54 { get; set; }
        public decimal SI_NO_55 { get; set; }
        public decimal SI_NO_56 { get; set; }
        public decimal SI_NO_57 { get; set; }
        public decimal SI_NO_58 { get; set; }
        public decimal SI_NO_59 { get; set; }
        public decimal SI_NO_60 { get; set; }
        public decimal TEMPS_DATA_INICI_DESTI { get; set; }
        public Nullable<decimal> SI_NO_61 { get; set; }
        public Nullable<decimal> SI_NO_62 { get; set; }
        public Nullable<decimal> SI_NO_63 { get; set; }
        public Nullable<decimal> SI_NO_64 { get; set; }
        public Nullable<decimal> SI_NO_65 { get; set; }
        public Nullable<decimal> SI_NO_66 { get; set; }
        public Nullable<decimal> SI_NO_67 { get; set; }
        public Nullable<decimal> SI_NO_68 { get; set; }
        public Nullable<decimal> SI_NO_69 { get; set; }
        public Nullable<decimal> SI_NO_70 { get; set; }
    }
}
