//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAP
    {
        public string CODI_EMP { get; set; }
        public string NUM_INTERN { get; set; }
        public string SERIE { get; set; }
        public string NUM_FAP { get; set; }
        public string SU_NUM_FAP { get; set; }
        public Nullable<System.DateTime> DATA_ALTA { get; set; }
        public Nullable<System.DateTime> DATA_EMISSIO { get; set; }
        public Nullable<System.DateTime> DATA_COBRO { get; set; }
        public Nullable<System.DateTime> DATA_CMP { get; set; }
        public Nullable<System.DateTime> DATA_VTO { get; set; }
        public string CODI_PRO { get; set; }
        public string CODI_MAG { get; set; }
        public string CODI_VHI { get; set; }
        public string CODI_FPA { get; set; }
        public string REFERENCIA { get; set; }
        public string USU_ALTA { get; set; }
        public string NUM_OTR { get; set; }
        public string OBS { get; set; }
        public string ESTAT { get; set; }
        public string CC { get; set; }
        public decimal IMP_BASE { get; set; }
        public decimal TANT_X100_DTE { get; set; }
        public decimal IMP_DTE { get; set; }
        public decimal IMP_IVA { get; set; }
        public decimal IMP_TOTAL { get; set; }
        public decimal EXTERN_SI_NO { get; set; }
    }
}
