//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAP_REC
    {
        public string NUM_INTERN { get; set; }
        public string CODI_EMP { get; set; }
        public string SERIE { get; set; }
        public string NUM_FAP { get; set; }
        public string SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA_COBRO { get; set; }
        public Nullable<System.DateTime> DATA_CMP { get; set; }
        public decimal IMP_REC { get; set; }
        public decimal CMP_SI_NO { get; set; }
        public Nullable<System.DateTime> DATA_VTO { get; set; }
        public decimal COBRAT_SI_NO { get; set; }
    }
}
