//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCT
    {
        public string CODI_EMP_FCT { get; set; }
        public string CODI_EMP_GEN { get; set; }
        public string NUM_FCT { get; set; }
        public string CODI_LOT { get; set; }
        public string CODI_DEV { get; set; }
        public Nullable<System.DateTime> DATA_ALTA { get; set; }
        public Nullable<System.DateTime> DATA_EMISSIO { get; set; }
        public Nullable<System.DateTime> DATA_DEV { get; set; }
        public Nullable<System.DateTime> DATA_MOROSA { get; set; }
        public Nullable<System.DateTime> DATA_COBRO { get; set; }
        public Nullable<System.DateTime> DATA_CMP { get; set; }
        public Nullable<System.DateTime> DATA_VTO { get; set; }
        public string ESTAT { get; set; }
        public decimal IMP_SRV { get; set; }
        public decimal TANT_X100_DTE { get; set; }
        public decimal IMP_DTE { get; set; }
        public decimal IMP_IVA { get; set; }
        public decimal IMP_TOTAL { get; set; }
        public string DES_BAN { get; set; }
        public string CC { get; set; }
        public string REFERENCIA { get; set; }
        public string OBS { get; set; }
        public string FORMA_PAGA { get; set; }
        public string NUM_INTERN { get; set; }
        public string SERIE { get; set; }
        public string INCIDENCIES { get; set; }
        public string CODI_CPT { get; set; }
        public Nullable<System.DateTime> DATA_DSK { get; set; }
        public string DATA_JUDICI { get; set; }
        public string ADRECA_ENVIAMENT { get; set; }
        public decimal IMP_BASE_IVA { get; set; }
        public decimal IMP_BASE_IVA_2 { get; set; }
        public decimal IMP_IVA_2 { get; set; }
        public decimal FORMAT_FACTURA { get; set; }
        public decimal ACCIO_FCT { get; set; }
        public string IBAN { get; set; }
        public Nullable<System.DateTime> DATA_INICI_PERIODE { get; set; }
        public Nullable<System.DateTime> DATA_FINAL_PERIODE { get; set; }
    }
}
