//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDI
    {
        public string SYS_215 { get; set; }
        public string CODI_TRB { get; set; }
        public string NUM_OTR { get; set; }
        public string CODI_INT { get; set; }
        public Nullable<System.DateTime> DATA_INICI { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public decimal TEMPS { get; set; }
        public string OBS { get; set; }
    }
}
