//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_PRE
    {
        public string CODI_FEE { get; set; }
        public string SYS_215 { get; set; }
        public decimal ORDRE { get; set; }
        public string PREGUNTA { get; set; }
        public decimal TEST_SI_NO { get; set; }
        public string TEST_1 { get; set; }
        public string TEST_2 { get; set; }
        public string TEST_3 { get; set; }
        public string TEST_4 { get; set; }
    }
}
