//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_TRB
    {
        public string CODI_FEE { get; set; }
        public string CODI_TRB { get; set; }
        public string SYS_215_FEE_PRE { get; set; }
        public string RESPOSTA { get; set; }
        public decimal RESPOSTA_TEST { get; set; }
    }
}
