//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTE
    {
        public string SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string CODI_EMP { get; set; }
        public string NIF { get; set; }
        public string DES { get; set; }
        public string NSERIET { get; set; }
        public string CODI_VHI { get; set; }
        public string NTTSIM { get; set; }
        public string IDTSIM { get; set; }
        public string OBS { get; set; }
    }
}
