//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS
    {
        public int HISID { get; set; }
        public string TYPE { get; set; }
        public string TABLENAME { get; set; }
        public string PRIMARYKEYFIELD { get; set; }
        public string PRIMARYKEYVALUE { get; set; }
        public string FIELDNAME { get; set; }
        public string OLDVALUE { get; set; }
        public string NEWVALUE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string USERNAME { get; set; }
    }
}
