//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_PRG
    {
        public int SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<System.DateTime> DATA_GENERA { get; set; }
        public string CODI_USU { get; set; }
        public string CODI_ZON { get; set; }
        public string FORM { get; set; }
        public string CODI_PRG { get; set; }
        public decimal FESTIU_SI_NO { get; set; }
        public decimal ENRUTATS_SRV { get; set; }
        public decimal NO_ENRUTATS_SRV { get; set; }
        public decimal TOTAL_SRV { get; set; }
        public decimal ESBORRATS_SRV { get; set; }
    }
}
