//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOS
    {
        public string CODI_HOS { get; set; }
        public string DES { get; set; }
        public string DOM { get; set; }
        public string POB { get; set; }
        public string TEL_1 { get; set; }
        public string TEL_2 { get; set; }
        public string FAX { get; set; }
        public string CODI_POB_SCS { get; set; }
        public string CODI_PRV { get; set; }
        public string CP { get; set; }
        public string PRV { get; set; }
        public string CODI_DIR { get; set; }
    }
}
