//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INF_TRB
    {
        public string SYS_215 { get; set; }
        public string CODI_TRB { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<System.DateTime> DATA_VIST { get; set; }
        public string DES { get; set; }
        public string TEXTE { get; set; }
        public string PATH_DOC { get; set; }
        public string APARTAT { get; set; }
        public decimal INACTIU_SI_NO { get; set; }
        public string DESTI { get; set; }
        public string CODI_TRB_ORIGEN { get; set; }
    }
}
