//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LLI_HIS
    {
        public int SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string CODI_USU { get; set; }
        public string LLISTAT { get; set; }
        public string FORM { get; set; }
        public string FILTRE { get; set; }
        public decimal REGISTRES { get; set; }
        public string NOM_CURSOR { get; set; }
    }
}
