//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOT
    {
        public string CODI_EMP_FCT { get; set; }
        public string CODI_LOT { get; set; }
        public decimal CENTRAL_SI_NO { get; set; }
        public string CLAUSULA { get; set; }
        public string DES { get; set; }
        public string NIF { get; set; }
        public string DIR { get; set; }
        public string POB { get; set; }
        public string CP { get; set; }
        public string PRV { get; set; }
        public string TEL_1 { get; set; }
        public string TEL_2 { get; set; }
        public string FAX { get; set; }
        public string CONTACTE_1 { get; set; }
        public string CONTACTE_2 { get; set; }
        public string OBS { get; set; }
        public decimal TARIFA_FRANQUICIA { get; set; }
        public decimal FRANQUICIA_SI_NO { get; set; }
        public decimal FRANQUICIA { get; set; }
        public decimal ZONA_AILLADA_SI_NO { get; set; }
        public decimal IMP_PART_VARIABLE { get; set; }
        public decimal IMP_CONCERTAT { get; set; }
        public decimal LOT_SI_NO { get; set; }
        public string CODI_CONCERT { get; set; }
        public string CODI_UP { get; set; }
        public string DES_BAN { get; set; }
        public string CC { get; set; }
        public string CODI_FPA { get; set; }
        public decimal TANT_X100_IVA { get; set; }
        public string NCT { get; set; }
        public string NCT_MOROS { get; set; }
        public string CODI_TAR { get; set; }
        public string CODI_TAR_OLD { get; set; }
        public decimal TANT_X100_DTE { get; set; }
        public string CONTACTE_3 { get; set; }
        public string DES_3 { get; set; }
        public string TEL_3 { get; set; }
        public string FAX_3 { get; set; }
        public string E_MAIL_3 { get; set; }
        public string CONTACTE_4 { get; set; }
        public string DES_4 { get; set; }
        public string TEL_4 { get; set; }
        public string FAX_4 { get; set; }
        public string E_MAIL_4 { get; set; }
        public string CONTACTE_5 { get; set; }
        public string DES_5 { get; set; }
        public string TEL_5 { get; set; }
        public string FAX_5 { get; set; }
        public string E_MAIL_5 { get; set; }
        public decimal FCT_X_PAC_SI_NO { get; set; }
        public string CODI_GRP { get; set; }
        public string DOCUMENTACIO { get; set; }
        public string HISTORIC { get; set; }
        public Nullable<System.DateTime> DATA_AVIS { get; set; }
        public string CODI_USU_AVIS { get; set; }
        public string COMENTARI_AVIS { get; set; }
        public string E_MAIL_URGENT { get; set; }
        public string E_MAIL_NORMAL { get; set; }
        public string E_MAIL_1 { get; set; }
        public string E_MAIL_2 { get; set; }
        public string DES_1 { get; set; }
        public string DES_2 { get; set; }
        public string FAX_1 { get; set; }
        public string FAX_2 { get; set; }
        public string TEL { get; set; }
        public string E_MAIL { get; set; }
        public string CODI_TFC { get; set; }
        public string CODI_CLI { get; set; }
        public string MARCA { get; set; }
        public string DOM_2 { get; set; }
        public string POS_2 { get; set; }
        public string POB_2 { get; set; }
        public string PRV_2 { get; set; }
        public string DOM_1 { get; set; }
        public string POS_1 { get; set; }
        public string POB_1 { get; set; }
        public string PRV_1 { get; set; }
        public string CODI_CCO { get; set; }
        public decimal TANT_X100_FCT { get; set; }
        public decimal QUIN_PREU { get; set; }
        public string SERIE_FACTURA { get; set; }
        public string TRAMITADOR { get; set; }
        public decimal FORMAT_FACTURA { get; set; }
        public string ADRECA_ENVIAMENT { get; set; }
        public decimal DTE_LINIA { get; set; }
        public string CODI_BAN { get; set; }
        public decimal COLOR { get; set; }
        public string CLAUSULA_1 { get; set; }
        public string NCT_INGRES { get; set; }
        public string NCT_BANC { get; set; }
        public string CODI_DPA { get; set; }
        public decimal DIA_PAGAMENT { get; set; }
        public int INACTIU_SI_NO { get; set; }
        public string COMENTARI_FACTURA { get; set; }
        public string CODI_TLO { get; set; }
        public string ESTAT_LOT { get; set; }
        public string IBAN { get; set; }
        public string SWIFT { get; set; }
        public decimal COLOR_TABLET { get; set; }
        public string CENTRE_ADMINISTRATIU { get; set; }
        public string CENTRE_ADMINISTRATIU_DES1 { get; set; }
        public string CENTRE_ADMINISTRATIU_DES2 { get; set; }
        public string CENTRE_ADMINISTRATIU_DES3 { get; set; }
        public string CONTACTE_FACTURAE { get; set; }
        public string TELEFON_FACTURAE { get; set; }
        public string EMAIL_FACTURAE { get; set; }
        public string CODI_PRC { get; set; }
        public string WEB { get; set; }
        public string FACEBOOK { get; set; }
        public string TWITTER { get; set; }
        public string LINKDIN { get; set; }
        public string CENTRE_ADMINISTRATIU2 { get; set; }
        public string CENTRE_ADMINISTRATIU3 { get; set; }
    }
}
