//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS
    {
        public string SYS_215 { get; set; }
        public string E_MAIL_RRHH { get; set; }
        public string E_MAIL_COORDINADOR { get; set; }
        public string E_MAIL_FORMACIO { get; set; }
        public string E_MAIL_MASTER { get; set; }
        public string E_MAIL_TRAFIC { get; set; }
        public string E_MAIL_PROGRAMACIO { get; set; }
    }
}
