//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAT
    {
        public string CODI_MAT { get; set; }
        public string DES { get; set; }
        public string AREA { get; set; }
        public string CODI_FAM { get; set; }
        public string CODI_INT { get; set; }
        public string CODI_GAM { get; set; }
        public string CODI_TMA { get; set; }
        public Nullable<System.DateTime> DATA_ALTA { get; set; }
        public string PARTIDA { get; set; }
        public decimal ESTOC_MINIM { get; set; }
        public string CODI_PRO { get; set; }
        public decimal LOT_SI_NO { get; set; }
        public decimal CADUCITAT_SI_NO { get; set; }
        public decimal ESTOC_SI_NO { get; set; }
        public decimal TEMPS { get; set; }
        public decimal COST_DARRER { get; set; }
        public decimal COST_MANUAL { get; set; }
        public decimal QUIN_COST { get; set; }
        public decimal TANT_X100_DTE { get; set; }
        public decimal TANT_X100_IVA { get; set; }
        public decimal PREU { get; set; }
        public decimal PREU_1 { get; set; }
        public decimal CHECK_LIST_SI_NO { get; set; }
        public string CODI_MAG { get; set; }
        public string REFERENCIA { get; set; }
        public string REFERENCIA_PRO { get; set; }
        public string FABRICANT { get; set; }
    }
}
