//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MET
    {
        public string CODI_MET { get; set; }
        public string DES { get; set; }
        public string ESPECIALITAT { get; set; }
        public string LLOC_1 { get; set; }
        public string LLOC_2 { get; set; }
        public string LLOC_3 { get; set; }
        public string CODI_PRC { get; set; }
        public string CODI_DEP { get; set; }
        public string NOM { get; set; }
        public string COGNOM_1 { get; set; }
        public string COGNOM_2 { get; set; }
        public string AREA_ASISTENCIAL { get; set; }
    }
}
