//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOD_FCT
    {
        public string CODI_USU { get; set; }
        public Nullable<System.DateTime> DATA_MOD { get; set; }
        public string PRG { get; set; }
        public decimal LIN_PRG { get; set; }
        public decimal REGISTRES { get; set; }
        public decimal REGISTRE { get; set; }
        public string CAMP { get; set; }
        public string CAMP_OLD { get; set; }
        public string CAMP_NEW { get; set; }
        public string NUM_INTERN { get; set; }
    }
}
