//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOC
    {
        public string NUM_NOC { get; set; }
        public string NUM_NOC_RELACIONAT { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<System.DateTime> DATA_LIMIT { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public string CODI_INC { get; set; }
        public string CODI_DEP_INICI { get; set; }
        public string RELATIU_A { get; set; }
        public string CODI_TRB { get; set; }
        public string DES { get; set; }
        public string DES_CAUSA { get; set; }
        public string DES_ACCIO { get; set; }
        public string DES_TANCA { get; set; }
        public string CODI_DEP_FINAL { get; set; }
    }
}
