//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUHSA
    {
        public string NUHSA1 { get; set; }
        public string TEL_1 { get; set; }
        public string DOM_1 { get; set; }
        public string CP { get; set; }
        public string LOCALITAT { get; set; }
        public string POBLACIO { get; set; }
        public string PROVINCIA { get; set; }
        public string MOVIL { get; set; }
        public string MAIL { get; set; }
        public Nullable<System.DateTime> DATA_NEIX { get; set; }
        public decimal SEXE { get; set; }
        public string NUSS { get; set; }
        public string SITUACIO_SS { get; set; }
        public string REGIMEN { get; set; }
        public string ASISTENCIA { get; set; }
        public string CAP { get; set; }
        public string ZONA_BASICA { get; set; }
        public string DISTRICTE { get; set; }
        public string NOM { get; set; }
        public string COGNOM_1 { get; set; }
        public string COGNOM_2 { get; set; }
        public string IDENTIFICADOR { get; set; }
    }
}
