//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTR
    {
        public string CODI_EMP { get; set; }
        public string CODI_EM_FCT { get; set; }
        public string NUM_OTR { get; set; }
        public string DES { get; set; }
        public string OBS { get; set; }
        public string VEHICLE { get; set; }
        public Nullable<System.DateTime> DATA_INICI { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public Nullable<System.DateTime> DATA_SINISTRE { get; set; }
        public string CODI_VHI { get; set; }
        public decimal KM { get; set; }
        public string USU_INICI { get; set; }
        public string USU_FINAL { get; set; }
        public decimal TOTAL { get; set; }
        public string CODI_TOT { get; set; }
        public string ESTAT { get; set; }
        public string CODI_TLL { get; set; }
        public Nullable<System.DateTime> DATA_PROPERA_REVISIO { get; set; }
        public Nullable<System.DateTime> DATA_PROPERA_ITV { get; set; }
        public decimal KM_PROPERA_REVISIO { get; set; }
        public Nullable<System.DateTime> DATA_PROPERA_TSANITARIA { get; set; }
        public Nullable<System.DateTime> DATA_PROPERA_TTRANSPORT { get; set; }
        public string NUM_PARTE { get; set; }
        public string REFERENCIA { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public decimal INCREMENT_LOT_SI_NO { get; set; }
        public string CODI_VHI_SUBSTITUCIO { get; set; }
        public string CODI_MAG { get; set; }
        public Nullable<System.DateTime> DATA_INICI_TEORICA { get; set; }
        public Nullable<System.DateTime> DATA_FINAL_TEORICA { get; set; }
        public string CODI_TRB { get; set; }
    }
}
