//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAC
    {
        public string CODI_EMP { get; set; }
        public string CODI_PAC { get; set; }
        public string NASS { get; set; }
        public string DNI { get; set; }
        public string CIP { get; set; }
        public string NOM { get; set; }
        public string COGNOMS { get; set; }
        public string COGNOM_1 { get; set; }
        public string COGNOM_2 { get; set; }
        public Nullable<System.DateTime> DATA_NEIX { get; set; }
        public string CODI_LOT { get; set; }
        public string POLISSA { get; set; }
        public string OBS { get; set; }
        public string TEL_1 { get; set; }
        public string TEL_2 { get; set; }
        public string TEL_3 { get; set; }
        public string TEL_4 { get; set; }
        public string CODI_CAP { get; set; }
        public string CODI_CLI { get; set; }
        public string CODI_USU { get; set; }
        public decimal HOME_SI_NO { get; set; }
        public string POSICIO_1 { get; set; }
        public string POSICIO_2 { get; set; }
        public string DOM_1 { get; set; }
        public string POB_1 { get; set; }
        public string DOM_2 { get; set; }
        public string POB_2 { get; set; }
        public string CONFLICTIVITAT { get; set; }
        public string PRV_1 { get; set; }
        public string PRV_2 { get; set; }
        public string COMENTARI { get; set; }
        public string CODI_UP { get; set; }
        public string PRIORITAT { get; set; }
        public string CODI_ZON_SRV { get; set; }
        public string CP_1 { get; set; }
        public string CP_2 { get; set; }
        public string CODI_AER { get; set; }
        public string CODI_UP_ESP { get; set; }
        public Nullable<System.DateTime> DATA_ALTA { get; set; }
        public decimal X_1 { get; set; }
        public decimal Y_1 { get; set; }
        public decimal X_2 { get; set; }
        public decimal Y_2 { get; set; }
        public decimal LATITUD_1 { get; set; }
        public decimal LONGITUD_1 { get; set; }
        public decimal LATITUD_2 { get; set; }
        public decimal LONGITUD_2 { get; set; }
        public decimal EXITUS_SI_NO { get; set; }
        public string CODI_EXTERN { get; set; }
        public decimal MINUTS_MARGE_RECOLLIR { get; set; }
        public decimal MINUTS_EN_RECOLLIR { get; set; }
        public decimal MINUTS_EN_DEIXAR { get; set; }
        public string OBS_SRV { get; set; }
        public string EMAIL { get; set; }
        public string PERSONA_CONTACTE { get; set; }
        public string DOM_11 { get; set; }
        public string DOM_22 { get; set; }
        public string CIP_SNS { get; set; }
        public string COBERTURA_SANITARIA { get; set; }
    }
}
