//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAR
    {
        public string CODI_PAR { get; set; }
        public string NUM_SRV { get; set; }
        public string CODI_LOT_1 { get; set; }
        public string CODI_LOT_2 { get; set; }
        public string CODI_LOT_3 { get; set; }
        public string VHI_1 { get; set; }
        public string VHI_2 { get; set; }
        public string MATRICULA_1 { get; set; }
        public string MATRICULA_2 { get; set; }
        public string DIR_1 { get; set; }
        public string DIR_2 { get; set; }
        public string POB_1 { get; set; }
        public string POB_2 { get; set; }
        public string PRV_1 { get; set; }
        public string PRV_2 { get; set; }
        public string TEL_1 { get; set; }
        public string TEL_2 { get; set; }
        public string CONDUCTOR { get; set; }
        public string PROPIETARI_1 { get; set; }
        public string PROPIETARI_2 { get; set; }
        public string POLISSA_1 { get; set; }
        public string POLISSA_2 { get; set; }
        public string REFERENCIA { get; set; }
        public string TRAMITADOR { get; set; }
        public string AUTORIZADOR { get; set; }
        public string OBS { get; set; }
        public string CARACTERISTIQUES { get; set; }
        public decimal TIPUS_ACCIDENT { get; set; }
        public string LLOC_OCUPA { get; set; }
        public string NOM_EMP { get; set; }
        public string NUM_COTITZACIO { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string LLOC_SINISTRE { get; set; }
        public string NOM { get; set; }
        public string COGNOMS { get; set; }
        public string TEL_PAC { get; set; }
        public string CP_1 { get; set; }
    }
}
