//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDA
    {
        public string CODI_PDA { get; set; }
        public string DES { get; set; }
        public string IP { get; set; }
        public string CODI_VHI { get; set; }
        public string PREGUNTA { get; set; }
        public string RESPOSTA { get; set; }
        public string VERSIO_FIRM { get; set; }
        public string REF_EPES { get; set; }
        public string TIPUS_TER { get; set; }
        public Nullable<short> EPES { get; set; }
        public Nullable<System.DateTime> DATA_MIS { get; set; }
        public Nullable<decimal> OPERADORA { get; set; }
    }
}
