//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLA
    {
        public int SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public decimal VEHICLES_AFECTATS { get; set; }
        public string ESTAT { get; set; }
        public string CODI_VHI { get; set; }
        public Nullable<System.DateTime> DATA_INICI { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public int SOBREESCRIBIR { get; set; }
        public string MATRICULA { get; set; }
    }
}
