//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLL
    {
        public string CODI_PLL { get; set; }
        public string DES { get; set; }
        public decimal DILLUNS_SI_NO_01 { get; set; }
        public decimal DIMARTS_SI_NO_01 { get; set; }
        public decimal DIMECRES_SI_NO_01 { get; set; }
        public decimal DIJOUS_SI_NO_01 { get; set; }
        public decimal DIVENDRES_SI_NO_01 { get; set; }
        public decimal DISSABTE_SI_NO_01 { get; set; }
        public decimal DIUMENGE_SI_NO_01 { get; set; }
        public decimal DIES_TREBALL_01 { get; set; }
        public decimal DIES_DESCANS_01 { get; set; }
        public decimal DILLUNS_SI_NO_02 { get; set; }
        public decimal DIMARTS_SI_NO_02 { get; set; }
        public decimal DIMECRES_SI_NO_02 { get; set; }
        public decimal DIJOUS_SI_NO_02 { get; set; }
        public decimal DIVENDRES_SI_NO_02 { get; set; }
        public decimal DISSABTE_SI_NO_02 { get; set; }
        public decimal DIUMENGE_SI_NO_02 { get; set; }
        public decimal DIES_TREBALL_02 { get; set; }
        public decimal DIES_DESCANS_02 { get; set; }
        public decimal DILLUNS_SI_NO_03 { get; set; }
        public decimal DIMARTS_SI_NO_03 { get; set; }
        public decimal DIMECRES_SI_NO_03 { get; set; }
        public decimal DIJOUS_SI_NO_03 { get; set; }
        public decimal DIVENDRES_SI_NO_03 { get; set; }
        public decimal DISSABTE_SI_NO_03 { get; set; }
        public decimal DIUMENGE_SI_NO_03 { get; set; }
        public decimal DIES_TREBALL_03 { get; set; }
        public decimal DIES_DESCANS_03 { get; set; }
        public decimal DILLUNS_SI_NO_04 { get; set; }
        public decimal DIMARTS_SI_NO_04 { get; set; }
        public decimal DIMECRES_SI_NO_04 { get; set; }
        public decimal DIJOUS_SI_NO_04 { get; set; }
        public decimal DIVENDRES_SI_NO_04 { get; set; }
        public decimal DISSABTE_SI_NO_04 { get; set; }
        public decimal DIUMENGE_SI_NO_04 { get; set; }
        public decimal DIES_TREBALL_04 { get; set; }
        public decimal DIES_DESCANS_04 { get; set; }
        public decimal NUM_DOTACIONS_01 { get; set; }
        public decimal NUM_DOTACIONS_02 { get; set; }
        public decimal NUM_DOTACIONS_03 { get; set; }
        public decimal NUM_DOTACIONS_04 { get; set; }
        public decimal INACTIVA_SI_NO { get; set; }
        public string CODI_TOR_1 { get; set; }
        public string CODI_TOR_2 { get; set; }
        public string CODI_TOR_3 { get; set; }
        public string CODI_TOR_4 { get; set; }
    }
}
