//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLL_VHI
    {
        public string CODI_PLL { get; set; }
        public string CODI_VHI { get; set; }
        public string NUM_DOTACIO { get; set; }
        public string CODI_TOR { get; set; }
        public string CODI_XOF { get; set; }
        public string SYS_215 { get; set; }
        public string CODI_AJU { get; set; }
        public Nullable<System.DateTime> DATA_INICI { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public string DES_VHI { get; set; }
        public string NOM_XOF { get; set; }
        public string NOM_AJU { get; set; }
    }
}
