//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLL_MES
    {
        public string CODI_PLL { get; set; }
        public string ANY_PLL { get; set; }
        public string MES_PLL { get; set; }
        public string CODI_TOR { get; set; }
        public string NUM_DOTACIO { get; set; }
        public decimal DIA_01_SI_NO { get; set; }
        public decimal DIA_02_SI_NO { get; set; }
        public decimal DIA_03_SI_NO { get; set; }
        public decimal DIA_04_SI_NO { get; set; }
        public decimal DIA_05_SI_NO { get; set; }
        public decimal DIA_06_SI_NO { get; set; }
        public decimal DIA_07_SI_NO { get; set; }
        public decimal DIA_08_SI_NO { get; set; }
        public decimal DIA_09_SI_NO { get; set; }
        public decimal DIA_10_SI_NO { get; set; }
        public decimal DIA_11_SI_NO { get; set; }
        public decimal DIA_12_SI_NO { get; set; }
        public decimal DIA_13_SI_NO { get; set; }
        public decimal DIA_14_SI_NO { get; set; }
        public decimal DIA_15_SI_NO { get; set; }
        public decimal DIA_16_SI_NO { get; set; }
        public decimal DIA_17_SI_NO { get; set; }
        public decimal DIA_18_SI_NO { get; set; }
        public decimal DIA_19_SI_NO { get; set; }
        public decimal DIA_20_SI_NO { get; set; }
        public decimal DIA_21_SI_NO { get; set; }
        public decimal DIA_22_SI_NO { get; set; }
        public decimal DIA_23_SI_NO { get; set; }
        public decimal DIA_24_SI_NO { get; set; }
        public decimal DIA_25_SI_NO { get; set; }
        public decimal DIA_26_SI_NO { get; set; }
        public decimal DIA_27_SI_NO { get; set; }
        public decimal DIA_28_SI_NO { get; set; }
        public decimal DIA_29_SI_NO { get; set; }
        public decimal DIA_30_SI_NO { get; set; }
        public decimal DIA_31_SI_NO { get; set; }
    }
}
