//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POB
    {
        public string CODI_POB { get; set; }
        public string DES { get; set; }
        public string CODI_PRV { get; set; }
        public string CODI_POB_SCS { get; set; }
        public string CODI_LOT { get; set; }
        public string CODI_BAS { get; set; }
        public string CODI_SEC { get; set; }
        public string CODI_ZON { get; set; }
        public string OBS { get; set; }
        public string CP { get; set; }
        public string POB_CP { get; set; }
        public string POB_EXTERNA { get; set; }
        public Nullable<System.DateTime> FESTIU_1 { get; set; }
        public Nullable<System.DateTime> FESTIU_2 { get; set; }
        public string CODI_RUT { get; set; }
    }
}
