//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POB_CP
    {
        public string POB_CP1 { get; set; }
        public string SYS_215 { get; set; }
        public string SIGLA { get; set; }
        public string CARRER { get; set; }
        public decimal IMPARELL_INF { get; set; }
        public decimal IMPARELL_SUP { get; set; }
        public decimal PARELL_INF { get; set; }
        public decimal PARELL_SUP { get; set; }
        public string CP { get; set; }
        public decimal UNIC_CP_SI_NO { get; set; }
        public decimal AUTOMATIC_SI_NO { get; set; }
    }
}
