//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRG_INC
    {
        public int SYS_215 { get; set; }
        public string CODI_INC { get; set; }
        public string CODI_PAC { get; set; }
        public string CODI_USU { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<System.DateTime> DATA_INC { get; set; }
        public string DIR_INICI { get; set; }
        public string POB_INICI { get; set; }
        public string DATA_RECOLLIDA { get; set; }
        public string DATA_INICI_SRV { get; set; }
        public string DATA_FINAL_SRV { get; set; }
        public decimal ANADA_SI_NO { get; set; }
        public decimal TORNADA_SI_NO { get; set; }
        public string OBS { get; set; }
        public string CODI_PRG { get; set; }
        public decimal ESTAT_INTERNET { get; set; }
        public decimal INTERNET_SI_NO { get; set; }
        public string TIPUS_INC { get; set; }
        public string CODI_RUT_IDA { get; set; }
        public string CODI_RUT_VUELTA { get; set; }
        public int NUMERO_INC { get; set; }
        public string DATA_DEIXAR_SRV_TORNADA { get; set; }
    }
}
