//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO
    {
        public string CODI_PRO { get; set; }
        public string DES { get; set; }
        public string POB { get; set; }
        public string POS { get; set; }
        public string PRV { get; set; }
        public string DOM { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string E_MAIL { get; set; }
        public string CONTACTE { get; set; }
        public string CODI_TPR { get; set; }
        public string CODI_FPA { get; set; }
        public decimal TANT_X100_DTE { get; set; }
        public string NIF { get; set; }
        public decimal ISO_SI_NO { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public decimal LATITUD { get; set; }
        public decimal LONGITUD { get; set; }
        public string TIPUS_PRO { get; set; }
        public string NCT { get; set; }
        public string OBS { get; set; }
        public decimal DIA_PAGAMENT { get; set; }
        public string AREA { get; set; }
        public string CODI_FAM { get; set; }
        public string CODI_TMA { get; set; }
        public string CODI_DPA { get; set; }
        public string ESTAT_PRO { get; set; }
        public int INACTIU_SI_NO { get; set; }
        public string WEB { get; set; }
        public string FACEBOOK { get; set; }
        public string TWITTER { get; set; }
        public string LINKDIN { get; set; }
    }
}
