//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUA
    {
        public string SYS_215 { get; set; }
        public string CODI_TRB { get; set; }
        public Nullable<System.DateTime> DATA_INICI { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public string CODI_EMP { get; set; }
        public string CODI_BAS { get; set; }
        public string CODI_VHI { get; set; }
        public string OBS { get; set; }
        public string CODI_TOR { get; set; }
        public string CODI_RUT { get; set; }
        public string TIPUS_TRB { get; set; }
        public decimal MARCA { get; set; }
        public string CODI_INC { get; set; }
        public string NOM { get; set; }
        public string CODI_TJO { get; set; }
        public string SYS_215_RELACIONAT { get; set; }
        public string CODI_TRB_RELACIONAT { get; set; }
        public Nullable<System.DateTime> DATA_INICI_REAL { get; set; }
        public Nullable<System.DateTime> DATA_FINAL_REAL { get; set; }
        public decimal GENERAT_PLANTILLA_SI_NO { get; set; }
        public decimal GENERAT_CPR_SI_NO { get; set; }
        public decimal GENERAT_MANUAL_SI_NO { get; set; }
        public string TIPUS_QUA { get; set; }
        public string DES_TJO { get; set; }
        public decimal FESTIU_SI_NO { get; set; }
        public Nullable<System.DateTime> DATA_INICI_ORIGINAL { get; set; }
        public Nullable<System.DateTime> DATA_FINAL_ORIGINAL { get; set; }
        public string SYS_215_RELACIONAT2 { get; set; }
        public string CODI_TRB_RELACIONAT2 { get; set; }
        public string SYS_215_RELACIONAT3 { get; set; }
        public string CODI_TRB_RELACIONAT3 { get; set; }
        public decimal BLOQUEJAT_SI_NO { get; set; }
        public Nullable<System.DateTime> DATA_BLOQUEIG { get; set; }
        public string COMENTARI { get; set; }
        public string CODI_ZON { get; set; }
        public string CODI_AGR { get; set; }
        public string CODI_SEC { get; set; }
        public decimal DIETES_SI_NO { get; set; }
        public decimal OK_SI_NO { get; set; }
        public string CODI_RCU { get; set; }
        public string CODI_SCC { get; set; }
        public decimal ADJUDICAT_VHI_SI_NO { get; set; }
        public decimal RODA_TORN { get; set; }
    }
}
