//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUA_BIS
    {
        public string SYS_215 { get; set; }
        public string CODI_TRB { get; set; }
        public Nullable<System.DateTime> DATA_INICI { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public string CODI_EMP { get; set; }
        public string CODI_TOR { get; set; }
        public string TIPUS_TRB { get; set; }
        public decimal MARCA { get; set; }
        public string NOM { get; set; }
        public string CODI_TJO { get; set; }
        public string DES_TJO { get; set; }
        public decimal FESTIU_SI_NO { get; set; }
        public string CODI_ZON { get; set; }
    }
}
