//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUA_INC
    {
        public string SYS_215_QUA { get; set; }
        public string SYS_215 { get; set; }
        public string CODI_TRB { get; set; }
        public string CODI_INC { get; set; }
        public string DES { get; set; }
        public string TIPUS_INC { get; set; }
        public Nullable<System.DateTime> DATA_INICI { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public string CODI_EMP { get; set; }
        public string CODI_BAS { get; set; }
        public string CODI_TRB_REAL { get; set; }
        public string OBS { get; set; }
        public string CODI_TOR { get; set; }
        public string CODI_RUT { get; set; }
        public string TIPUS_TRB { get; set; }
        public Nullable<System.DateTime> DATA_INICI_REAL { get; set; }
        public Nullable<System.DateTime> DATA_FINAL_TEORIC { get; set; }
        public Nullable<System.DateTime> DATA_FINAL_REAL { get; set; }
        public Nullable<System.DateTime> DATA_INICI_TEORIC { get; set; }
    }
}
