//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCL
    {
        public string SYS_215 { get; set; }
        public string DES { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<System.DateTime> DATA_RECLAMACIO { get; set; }
        public string CONTACTE { get; set; }
        public string CODI_INC { get; set; }
        public string NUM_SRV { get; set; }
        public string CODI_PAC { get; set; }
        public string CODI_TRB { get; set; }
        public string CODI_VHI { get; set; }
        public string PROCEDENCIA_RCL { get; set; }
        public string TIPUS_RCL { get; set; }
        public string ESTAT_RCL { get; set; }
        public string ACCIO_CORRECTORA { get; set; }
        public string OBS { get; set; }
        public string RECEPCIO_RCL { get; set; }
        public string CODI_AJU { get; set; }
        public string NUM_RCL { get; set; }
        public Nullable<System.DateTime> DATA_NOTIFICACIO { get; set; }
        public Nullable<System.DateTime> DATA_RESOLUCIO { get; set; }
        public string MOTIU_RCL { get; set; }
        public string AREA_PRODUCTIVA_RCL { get; set; }
        public string MOTIUS_RCL { get; set; }
    }
}
