//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REG_DIA
    {
        public string SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA_ALTA { get; set; }
        public Nullable<System.DateTime> DATA_REG { get; set; }
        public string OBS { get; set; }
        public string CODI_USU { get; set; }
        public string CODI_EMP { get; set; }
        public string CODI_INC { get; set; }
        public decimal QUALITAT_SI_NO { get; set; }
        public string CODI_TRB { get; set; }
        public string CODI_MOT { get; set; }
        public string ESTAT_REG_DIA { get; set; }
        public string CODI_VHI { get; set; }
    }
}
