//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUT
    {
        public string CODI_RUT { get; set; }
        public string DES { get; set; }
        public string CODI_VHI { get; set; }
        public string POSICIO { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public string CODI_DIR_FINAL { get; set; }
        public string DIR_FINAL { get; set; }
        public string POB_FINAL { get; set; }
        public decimal ACTIVA_SI_NO { get; set; }
        public string OBS { get; set; }
        public string CODI_UP { get; set; }
        public string CP { get; set; }
        public string AVIS { get; set; }
        public string CODI_ZON { get; set; }
    }
}
