//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCS
    {
        public string CODI_SCS { get; set; }
        public string DES { get; set; }
        public string CIF { get; set; }
        public string DIR { get; set; }
        public string CP { get; set; }
        public string POB { get; set; }
        public string PRV { get; set; }
        public string TEL_1 { get; set; }
        public string TEL_2 { get; set; }
        public string TEL_3 { get; set; }
        public string TEL_4 { get; set; }
        public string FAX_1 { get; set; }
        public string FAX_2 { get; set; }
        public string E_MAIL_1 { get; set; }
        public string E_MAIL_2 { get; set; }
        public string E_MAIL_3 { get; set; }
    }
}
