//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS
    {
        public string SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA_ALTA { get; set; }
        public Nullable<System.DateTime> DATA_ENVIAMENT { get; set; }
        public Nullable<System.DateTime> DATA_ACUSE { get; set; }
        public string TELEFON_DESTI { get; set; }
        public string TEXT_ENVIAMENT { get; set; }
        public string TEXT_ACUSE { get; set; }
        public string ESTAT { get; set; }
        public string IDSMS { get; set; }
        public string FORM_ENVIAMENT { get; set; }
        public string TIPUS_ENVIAMENT { get; set; }
        public string CODI_PAC { get; set; }
        public string CODI_TRB { get; set; }
        public string CODI_VHI { get; set; }
        public string NUM_SRV { get; set; }
    }
}
