//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_ASS
    {
        public string SYS_215 { get; set; }
        public string NUM_SRV { get; set; }
        public Nullable<System.DateTime> DATA_ALTA { get; set; }
        public Nullable<System.DateTime> DATA_INICI { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public string NOM_PACIENT { get; set; }
        public string COGNOMS_PACIENT { get; set; }
        public string DNI { get; set; }
        public string TIPUS_ASSISTENCIA { get; set; }
        public string DESCRIPCIO_ASSISTENCIA { get; set; }
        public string MATERIALS_ASSISTENCIA { get; set; }
        public string PATH_DOC { get; set; }
        public Nullable<decimal> GENERA_EVACUACIO_SI_NO { get; set; }
        public string NUM_SRV_GENERAT { get; set; }
        public Nullable<decimal> EDAT { get; set; }
        public string HOSPITAL_DESTI { get; set; }
        public string VHI_EVACUACIO { get; set; }
    }
}
