//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_LLI
    {
        public string OPCIO { get; set; }
        public decimal SUB_OPCIO_1 { get; set; }
        public decimal SUB_OPCIO_2 { get; set; }
        public string DES_1 { get; set; }
        public string DES_2 { get; set; }
        public string DES_3 { get; set; }
        public string DES_4 { get; set; }
        public decimal ESTANDARD_SI_NO { get; set; }
        public decimal INFORMACIO_SI_NO { get; set; }
        public decimal NUM_BOTO { get; set; }
        public string NOM_REPORT { get; set; }
        public string NOM_SEL { get; set; }
        public string PARAMETRE { get; set; }
    }
}
