//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_MEN
    {
        public decimal N1 { get; set; }
        public decimal N2 { get; set; }
        public string TIPO { get; set; }
        public string DESCRIPCION1 { get; set; }
        public string DESCRIPCION2 { get; set; }
        public string DESCRIPCION3 { get; set; }
        public string DESCRIPCION4 { get; set; }
        public string FORM { get; set; }
        public string INSTRUCCION { get; set; }
        public string HOTKEY { get; set; }
        public decimal PICTURE_SI_NO { get; set; }
        public string PICTURE { get; set; }
        public string TEXTOSTATUS1 { get; set; }
        public string TEXTOSTATUS2 { get; set; }
        public string TEXTOSTATUS3 { get; set; }
        public string TEXTOSTATUS4 { get; set; }
        public decimal ACTIVADO { get; set; }
        public decimal ESTANDARD_SI_NO { get; set; }
        public decimal FACXXI { get; set; }
        public decimal CENXXI { get; set; }
        public decimal GAMXXI { get; set; }
        public decimal TALXXI { get; set; }
        public decimal VHIXXI { get; set; }
        public decimal PROXXI { get; set; }
        public decimal PUNT_OBLIGAT { get; set; }
        public decimal TELXXI { get; set; }
        public decimal PERXXI { get; set; }
        public decimal WEBXXI { get; set; }
    }
}
