//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CON
    {
        public string ELEMENTO { get; set; }
        public Nullable<decimal> NUMERO_ACTUAL { get; set; }
        public Nullable<int> CONTADOR { get; set; }
    }
}
