//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEL_HIS
    {
        public int SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA_INICI { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public string CODI_USU { get; set; }
        public string ACCIO { get; set; }
        public string EXTENSIO { get; set; }
        public string TELEFON { get; set; }
        public string CODI_PAC { get; set; }
        public string NOM_PAC { get; set; }
        public string CODI_AGE { get; set; }
        public string NOM_AGE { get; set; }
        public string TEMPS_TRUCADA_MINUTS { get; set; }
        public decimal TEMPS_TRUCADA_SEGONS { get; set; }
        public decimal TEMPS_A_CONTESTAR { get; set; }
        public decimal SHA_CONTESTAT_SI_NO { get; set; }
    }
}
