//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLL
    {
        public string CODI_TLL { get; set; }
        public string DES { get; set; }
        public string TIPUS_TLL { get; set; }
        public string DOM { get; set; }
        public string POB { get; set; }
        public string PRV { get; set; }
        public string POS { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string E_MAIL { get; set; }
        public string CONTACTES { get; set; }
        public decimal EXTERN_SI_NO { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public decimal LATITUD { get; set; }
        public decimal LONGITUD { get; set; }
    }
}
