//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOR
    {
        public string CODI_TOR { get; set; }
        public string DES { get; set; }
        public string HORA_FINAL { get; set; }
        public string HORA_INICI { get; set; }
        public string HORA_INICI_PARTIT { get; set; }
        public string HORA_FINAL_PARTIT { get; set; }
        public decimal COLOR { get; set; }
        public decimal SEGUENT_DIA_SI_NO { get; set; }
        public decimal TEMPS_APAT { get; set; }
    }
}
