//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRB
    {
        public string CODI_TRB { get; set; }
        public string NOM { get; set; }
        public string COGNOMS { get; set; }
        public string DNI { get; set; }
        public string NASS { get; set; }
        public string DIR { get; set; }
        public string CP { get; set; }
        public string POB { get; set; }
        public string PRV { get; set; }
        public string TEL_1 { get; set; }
        public string TEL_2 { get; set; }
        public string TEL_3 { get; set; }
        public string OBS { get; set; }
        public string CATEGORIA { get; set; }
        public string CONTRATO { get; set; }
        public string COMENTARI { get; set; }
        public Nullable<System.DateTime> DATA_INICI { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public decimal TIPUS_ACCES { get; set; }
        public Nullable<System.DateTime> DATA_NEIX { get; set; }
        public decimal XOFER_SI_NO { get; set; }
        public decimal AJUDANT_SI_NO { get; set; }
        public decimal ACTIU_SI_NO { get; set; }
        public string CODI_BASE { get; set; }
        public string CODI_ZON { get; set; }
        public string CODI_SEC { get; set; }
        public string CODI_EMP { get; set; }
        public decimal MINUTS_DINAR { get; set; }
        public decimal MINUTS_SOPAR { get; set; }
        public decimal MINUTS_ESMORTZAR { get; set; }
        public string CODI_TOR { get; set; }
        public decimal METGE_SI_NO { get; set; }
        public decimal ENFER_SI_NO { get; set; }
        public string CODI_RUT { get; set; }
        public string NUM_TTS { get; set; }
        public string CARNETS { get; set; }
        public string CODI_TAR_EXTRA { get; set; }
        public string CODI_TAR_HORA { get; set; }
        public string TALLES { get; set; }
        public string CODI_CCO { get; set; }
        public string NUM_FCT { get; set; }
        public string CC { get; set; }
        public Nullable<System.DateTime> DATA_RENOVAR { get; set; }
        public decimal TANT_X100_IVA { get; set; }
        public decimal TANT_X100_IRPF { get; set; }
        public Nullable<System.DateTime> DATA_RENOVA { get; set; }
        public string AVIS { get; set; }
        public string CODI_CAT { get; set; }
        public string CODI_AER { get; set; }
        public string PWD_WEB { get; set; }
        public string E_MAIL { get; set; }
        public decimal TIPUS_WEB { get; set; }
        public string ESTAT_CIVIL { get; set; }
        public string NOM_PARELLA { get; set; }
        public string DNI_PARELLA { get; set; }
        public string TREBALL_ANTERIOR_1 { get; set; }
        public string TREBALL_ANTERIOR_2 { get; set; }
        public string TREBALL_ANTERIOR_3 { get; set; }
        public string CARREC_ANTERIOR_1 { get; set; }
        public string CARREC_ANTERIOR_2 { get; set; }
        public string CARREC_ANTERIOR_3 { get; set; }
        public decimal FILLS { get; set; }
        public string PWD { get; set; }
        public string CODI_EXTERN { get; set; }
        public string SEXE { get; set; }
        public string CODI_VHI { get; set; }
        public Nullable<System.DateTime> DATA_ANTI { get; set; }
        public decimal ALTRES_SI_NO { get; set; }
        public string IDIOMA { get; set; }
        public string CODI_TCO { get; set; }
        public decimal TARJETA { get; set; }
        public decimal URGENT_SI_NO { get; set; }
        public Nullable<System.DateTime> DATA_FILL_1 { get; set; }
        public Nullable<System.DateTime> DATA_FILL_2 { get; set; }
        public Nullable<System.DateTime> DATA_FILL_3 { get; set; }
        public Nullable<System.DateTime> DATA_FILL_4 { get; set; }
        public string IBAN { get; set; }
        public Nullable<System.DateTime> DATA_FILL_5 { get; set; }
        public decimal TES_SI_NO { get; set; }
        public string CODI_AGR { get; set; }
        public decimal CONCILIACIO_VIDA_FAMILIAR_SI_NO { get; set; }
    }
}
