//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRB_PLL
    {
        public string CODI_TRB { get; set; }
        public string CODI_TORN_LUNES_MATI_1 { get; set; }
        public string CODI_TORN_MARTES_MATI_1 { get; set; }
        public string CODI_TORN_MIERCOLES_MATI_1 { get; set; }
        public string CODI_TORN_JUEVES_MATI_1 { get; set; }
        public string CODI_TORN_VIERNES_MATI_1 { get; set; }
        public string CODI_TORN_SABADO_MATI_1 { get; set; }
        public string CODI_TORN_DOMINGO_MATI_1 { get; set; }
        public string CODI_TORN_LUNES_TARDA_1 { get; set; }
        public string CODI_TORN_MARTES_TARDA_1 { get; set; }
        public string CODI_TORN_MIERCOLES_TARDA_1 { get; set; }
        public string CODI_TORN_JUEVES_TARDA_1 { get; set; }
        public string CODI_TORN_VIERNES_TARDA_1 { get; set; }
        public string CODI_TORN_SABADO_TARDA_1 { get; set; }
        public string CODI_TORN_DOMINGO_TARDA_1 { get; set; }
        public string CODI_TJO_LUNES_1 { get; set; }
        public string CODI_TJO_MARTES_1 { get; set; }
        public string CODI_TJO_MIERCOLES_1 { get; set; }
        public string CODI_TJO_JUEVES_1 { get; set; }
        public string CODI_TJO_VIERNES_1 { get; set; }
        public string CODI_TJO_SABADO_1 { get; set; }
        public string CODI_TJO_DOMINGO_1 { get; set; }
        public string CODI_TORN_LUNES_MATI_2 { get; set; }
        public string CODI_TORN_MARTES_MATI_2 { get; set; }
        public string CODI_TORN_MIERCOLES_MATI_2 { get; set; }
        public string CODI_TORN_JUEVES_MATI_2 { get; set; }
        public string CODI_TORN_VIERNES_MATI_2 { get; set; }
        public string CODI_TORN_SABADO_MATI_2 { get; set; }
        public string CODI_TORN_DOMINGO_MATI_2 { get; set; }
        public string CODI_TORN_LUNES_TARDA_2 { get; set; }
        public string CODI_TORN_MARTES_TARDA_2 { get; set; }
        public string CODI_TORN_MIERCOLES_TARDA_2 { get; set; }
        public string CODI_TORN_JUEVES_TARDA_2 { get; set; }
        public string CODI_TORN_VIERNES_TARDA_2 { get; set; }
        public string CODI_TORN_SABADO_TARDA_2 { get; set; }
        public string CODI_TORN_DOMINGO_TARDA_2 { get; set; }
        public string CODI_TJO_LUNES_2 { get; set; }
        public string CODI_TJO_MARTES_2 { get; set; }
        public string CODI_TJO_MIERCOLES_2 { get; set; }
        public string CODI_TJO_JUEVES_2 { get; set; }
        public string CODI_TJO_VIERNES_2 { get; set; }
        public string CODI_TJO_SABADO_2 { get; set; }
        public string CODI_TJO_DOMINGO_2 { get; set; }
        public string CODI_TORN_LUNES_MATI_3 { get; set; }
        public string CODI_TORN_MARTES_MATI_3 { get; set; }
        public string CODI_TORN_MIERCOLES_MATI_3 { get; set; }
        public string CODI_TORN_JUEVES_MATI_3 { get; set; }
        public string CODI_TORN_VIERNES_MATI_3 { get; set; }
        public string CODI_TORN_SABADO_MATI_3 { get; set; }
        public string CODI_TORN_DOMINGO_MATI_3 { get; set; }
        public string CODI_TORN_LUNES_TARDA_3 { get; set; }
        public string CODI_TORN_MARTES_TARDA_3 { get; set; }
        public string CODI_TORN_MIERCOLES_TARDA_3 { get; set; }
        public string CODI_TORN_JUEVES_TARDA_3 { get; set; }
        public string CODI_TORN_VIERNES_TARDA_3 { get; set; }
        public string CODI_TORN_SABADO_TARDA_3 { get; set; }
        public string CODI_TORN_DOMINGO_TARDA_3 { get; set; }
        public string CODI_TJO_LUNES_3 { get; set; }
        public string CODI_TJO_MARTES_3 { get; set; }
        public string CODI_TJO_MIERCOLES_3 { get; set; }
        public string CODI_TJO_JUEVES_3 { get; set; }
        public string CODI_TJO_VIERNES_3 { get; set; }
        public string CODI_TJO_SABADO_3 { get; set; }
        public string CODI_TJO_DOMINGO_3 { get; set; }
        public string CODI_TORN_LUNES_MATI_4 { get; set; }
        public string CODI_TORN_MARTES_MATI_4 { get; set; }
        public string CODI_TORN_MIERCOLES_MATI_4 { get; set; }
        public string CODI_TORN_JUEVES_MATI_4 { get; set; }
        public string CODI_TORN_VIERNES_MATI_4 { get; set; }
        public string CODI_TORN_SABADO_MATI_4 { get; set; }
        public string CODI_TORN_DOMINGO_MATI_4 { get; set; }
        public string CODI_TORN_LUNES_TARDA_4 { get; set; }
        public string CODI_TORN_MARTES_TARDA_4 { get; set; }
        public string CODI_TORN_MIERCOLES_TARDA_4 { get; set; }
        public string CODI_TORN_JUEVES_TARDA_4 { get; set; }
        public string CODI_TORN_VIERNES_TARDA_4 { get; set; }
        public string CODI_TORN_SABADO_TARDA_4 { get; set; }
        public string CODI_TORN_DOMINGO_TARDA_4 { get; set; }
        public string CODI_TJO_LUNES_4 { get; set; }
        public string CODI_TJO_MARTES_4 { get; set; }
        public string CODI_TJO_MIERCOLES_4 { get; set; }
        public string CODI_TJO_JUEVES_4 { get; set; }
        public string CODI_TJO_VIERNES_4 { get; set; }
        public string CODI_TJO_SABADO_4 { get; set; }
        public string CODI_TJO_DOMINGO_4 { get; set; }
        public decimal SETMANA { get; set; }
        public string VHI_D_1_1 { get; set; }
        public string VHI_D_2_1 { get; set; }
        public string VHI_D_3_1 { get; set; }
        public string VHI_D_4_1 { get; set; }
        public string VHI_D_5_1 { get; set; }
        public string VHI_D_6_1 { get; set; }
        public string VHI_D_7_1 { get; set; }
        public string VHI_D_1_2 { get; set; }
        public string VHI_D_2_2 { get; set; }
        public string VHI_D_3_2 { get; set; }
        public string VHI_D_4_2 { get; set; }
        public string VHI_D_5_2 { get; set; }
        public string VHI_D_6_2 { get; set; }
        public string VHI_D_7_2 { get; set; }
        public string VHI_D_1_3 { get; set; }
        public string VHI_D_2_3 { get; set; }
        public string VHI_D_3_3 { get; set; }
        public string VHI_D_4_3 { get; set; }
        public string VHI_D_5_3 { get; set; }
        public string VHI_D_6_3 { get; set; }
        public string VHI_D_7_3 { get; set; }
        public string VHI_D_1_4 { get; set; }
        public string VHI_D_2_4 { get; set; }
        public string VHI_D_3_4 { get; set; }
        public string VHI_D_4_4 { get; set; }
        public string VHI_D_5_4 { get; set; }
        public string VHI_D_6_4 { get; set; }
        public string VHI_D_7_4 { get; set; }
        public decimal FILA { get; set; }
    }
}
