//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRB_VES
    {
        public int SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string CODI_TRB { get; set; }
        public string CODI_MAT { get; set; }
        public string DES { get; set; }
        public Nullable<System.DateTime> DATA_DARRERA_ENTREGA { get; set; }
        public decimal UNITATS_ENTREGADES { get; set; }
        public string OBS { get; set; }
    }
}
