//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRB_FOR
    {
        public string SYS_215 { get; set; }
        public string CODI_TRB { get; set; }
        public Nullable<System.DateTime> DATA_INICI { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public string TITOL { get; set; }
        public decimal HORES { get; set; }
        public string LLOC { get; set; }
        public string OBS { get; set; }
        public string PATH_DOC { get; set; }
        public string TIPUS_FORMACIO { get; set; }
        public decimal TITOL_ACADEMIC { get; set; }
        public string FORMADOR { get; set; }
        public string ENTITAT_ORGANITZA { get; set; }
        public string CODI_FOR { get; set; }
        public string FORMACIO { get; set; }
    }
}
