//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRB_HUE
    {
        public int ID { get; set; }
        public string CODI_TRB { get; set; }
        public string NUMERO_DIT { get; set; }
        public byte[] PLANTILLA { get; set; }
        public string OBS { get; set; }
    }
}
