//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRB_INC
    {
        public string CODI_TRB { get; set; }
        public decimal INCIDENCIA { get; set; }
        public string SYS_215 { get; set; }
        public string CODI_VHI { get; set; }
        public string LLOC { get; set; }
        public decimal AMONESTACIO { get; set; }
        public string DOCUMENT_1 { get; set; }
        public string DOCUMENT_2 { get; set; }
        public string DOCUMENT_3 { get; set; }
        public string OBS { get; set; }
        public Nullable<System.DateTime> DATA_ALTA { get; set; }
        public Nullable<System.DateTime> DATA_INCIDENCIA { get; set; }
        public decimal MINUTS { get; set; }
        public decimal IMP { get; set; }
        public decimal DIES_SANCIO { get; set; }
    }
}
