//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRB_HIS
    {
        public Nullable<System.DateTime> DATA { get; set; }
        public string CODI_TRB { get; set; }
        public string NOM { get; set; }
        public string ENTRA_SURT { get; set; }
        public decimal ACCIO { get; set; }
        public string CODI_VHI { get; set; }
        public string CODI_USU { get; set; }
        public int SYS_215 { get; set; }
    }
}
