//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSNUX
    {
        public int SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<System.DateTime> DATA_TSNUX { get; set; }
        public Nullable<System.DateTime> DATA_MIS { get; set; }
        public string REFERENCIA { get; set; }
        public string NUM_SRV { get; set; }
        public string NUM_ERROR { get; set; }
        public string DES_ERROR { get; set; }
        public string TIPUS { get; set; }
        public string CODI_VHI { get; set; }
        public string TEXT_ENVIAT { get; set; }
        public int SYS_215_PLA { get; set; }
        public string ESTAT { get; set; }
        public int IDACTIVIDAD { get; set; }
        public int IDTRASLADO { get; set; }
        public int INTENTS { get; set; }
        public int SYS_215_DAT_TOR { get; set; }
        public string SYS_215_VHI_INC { get; set; }
        public string CODI_PRG { get; set; }
    }
}
