//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USU
    {
        public string CODI_USU { get; set; }
        public string NOM { get; set; }
        public string PWD { get; set; }
        public string IDIOMA { get; set; }
        public string CODI_DEP { get; set; }
        public string CODI_PRC { get; set; }
        public string CODI_LOT_1 { get; set; }
        public string CODI_LOT_2 { get; set; }
        public string CODI_LOT_3 { get; set; }
        public string CODI_LOT_4 { get; set; }
        public decimal CENXXI { get; set; }
        public decimal FACXXI { get; set; }
        public decimal GAMXXI { get; set; }
        public decimal TORXXI { get; set; }
        public decimal WEB_SI_NO { get; set; }
        public decimal TALXXI { get; set; }
        public decimal VHIXXI { get; set; }
        public decimal PROXXI { get; set; }
        public decimal SUPERVISOR { get; set; }
        public string CODI_CAP { get; set; }
        public string CODI_LOT { get; set; }
        public string CODI_EMP { get; set; }
        public string CODI_DIR { get; set; }
        public decimal TELXXI { get; set; }
        public decimal PERXXI { get; set; }
        public string E_MAIL { get; set; }
        public string CODI_AER { get; set; }
        public string CODI_USU_ROL { get; set; }
        public decimal CANVIA_PWD_SI_NO { get; set; }
        public decimal GOOGLE_SI_NO { get; set; }
        public decimal MANIPULA_SERVEIS_SI_NO { get; set; }
        public decimal WEBXXI { get; set; }
        public decimal ACTIU_SI_NO { get; set; }
        public string IDIOMA_WEB { get; set; }
        public decimal MANIPULA_QUADRANT_SI_NO { get; set; }
        public string E_MAIL_1 { get; set; }
        public decimal ACCESS_CATEGORIA { get; set; }
        public int NIVELL_SEGURETAT_DOCUMENTS { get; set; }
        public decimal NIVELL_SEGURETAT_PORTALWEB { get; set; }
        public Nullable<System.DateTime> DATA_ERROR_LOGIN { get; set; }
        public string CODI_USU_GAMWEB { get; set; }
        public string NIVELL_USU_GAMWEB { get; set; }
    }
}
