//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USU_DEF
    {
        public string CODI_USU { get; set; }
        public string CODI_DIG { get; set; }
        public string CODI_PRC { get; set; }
        public string CODI_TRA { get; set; }
        public string CODI_TVH { get; set; }
        public string CODI_SIN { get; set; }
        public string CODI_TFC { get; set; }
        public string CODI_TRM { get; set; }
        public string CODI_UP { get; set; }
        public string CODI_LOT { get; set; }
        public string CODI_EMP { get; set; }
        public string RESOLUCIO_FORM_COORDINACIO { get; set; }
        public string POB { get; set; }
        public decimal LEFT_GRID_ADJUDICATS { get; set; }
        public decimal AMPLE_GRID_ADJUDICATS { get; set; }
        public decimal HEIGHT_GRID_ADJUDICATS { get; set; }
        public decimal TOP_GRID_ADJUDICATS { get; set; }
        public decimal HEIGHT_GRID_PENDENTS { get; set; }
        public decimal TOP_GRID_PENDENTS { get; set; }
        public decimal REFRESC_COORDINACIO { get; set; }
        public decimal NEGRETA_COORDINACIO_SI_NO { get; set; }
        public decimal COLOR_GRID_PENDENTS { get; set; }
        public decimal COLOR_GRID_ADJUDICATS { get; set; }
        public decimal BEEP_GRID_ADJUDICATS_SI_NO { get; set; }
        public decimal LEFT_GRID_PENDENTS { get; set; }
        public decimal AMPLE_GRID_PENDENTS { get; set; }
        public string CODI_ZON_SRV { get; set; }
        public string CODI_DEP { get; set; }
        public string CODI_DIR { get; set; }
        public decimal GOOGLE_SI_NO { get; set; }
        public string DOMINIO { get; set; }
        public string CLAVE { get; set; }
        public decimal INICI_RECEPCIO { get; set; }
        public decimal ACCIONS_ASI { get; set; }
        public decimal DEMORA_COORDINACIO { get; set; }
        public string CODI_RUT { get; set; }
        public string CODI_MAG { get; set; }
        public string CODI_TLL { get; set; }
        public string CODI_TAR { get; set; }
        public decimal BEEP_GRID_MISSATGES_SI_NO { get; set; }
        public decimal AJUSTAR_PANTALLES_SUPERIOR { get; set; }
        public string CODI_ZON_SRV_1 { get; set; }
        public string CODI_ZON_SRV_2 { get; set; }
        public string CODI_ZON_SRV_3 { get; set; }
    }
}
