//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USU_MEN
    {
        public string CODI_USU { get; set; }
        public string FORM { get; set; }
        public decimal PERMIS_ALTA { get; set; }
        public decimal PERMIS_EDITAR { get; set; }
        public decimal PERMIS_ELIMINAR { get; set; }
        public decimal PERMIS_IMPRESSIO { get; set; }
        public decimal PERMIS_NO_ACCES { get; set; }
        public int SYS_215_PK { get; set; }
    }
}
