//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHI
    {
        public string CODI_EMP { get; set; }
        public string CODI_EMP_FCT { get; set; }
        public string CODI_VHI { get; set; }
        public string DES { get; set; }
        public string CODI_XOF { get; set; }
        public string CODI_AJU { get; set; }
        public string CODI_MVH { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public string MATRICULA { get; set; }
        public Nullable<System.DateTime> DATA_COMPRA { get; set; }
        public string NUM_BAS { get; set; }
        public decimal INACTIU_SI_NO { get; set; }
        public decimal CONTROL_GPS_SI_NO { get; set; }
        public decimal ACTIVAR_GPS_SI_NO { get; set; }
        public string TEL_VHI { get; set; }
        public string CODI_BAS { get; set; }
        public string CODI_ZON { get; set; }
        public string CODI_SEC { get; set; }
        public string CODI_LOT_1 { get; set; }
        public string CODI_LOT_2 { get; set; }
        public string CODI_LOT_3 { get; set; }
        public string CODI_LOT_4 { get; set; }
        public decimal PLACES { get; set; }
        public string OBS { get; set; }
        public decimal KM_ACTUALS { get; set; }
        public decimal IMP_COMPRA { get; set; }
        public decimal IMP_CARROSSAR { get; set; }
        public decimal IMP_EQUIP_MEDIC { get; set; }
        public Nullable<System.DateTime> DATA_INICI_APAT { get; set; }
        public Nullable<System.DateTime> DATA_FINAL_APAT { get; set; }
        public string CODI_TVH { get; set; }
        public string CODI_TFC { get; set; }
        public decimal PES { get; set; }
        public decimal LONGITUT { get; set; }
        public decimal AMPLE { get; set; }
        public decimal ALT { get; set; }
        public string HORA_INICI_MATI { get; set; }
        public string HORA_FINAL_MATI { get; set; }
        public string HORA_INICI_TARDA { get; set; }
        public string HORA_FINAL_TARDA { get; set; }
        public string CODI_TRA { get; set; }
        public string CODI_VHI_1 { get; set; }
        public Nullable<System.DateTime> DATA_BAIXA { get; set; }
        public string CODI_DIR_FINAL { get; set; }
        public string DIR_FINAL { get; set; }
        public string DIR_FINAL_1 { get; set; }
        public string POB_FINAL { get; set; }
        public string CODI_MET { get; set; }
        public string CODI_ENF { get; set; }
        public string TIPUS_APAT { get; set; }
        public decimal DAT_SI_NO { get; set; }
        public decimal PDA_SI_NO { get; set; }
        public string TIPUS_COMPRA { get; set; }
        public string CODI_TOR { get; set; }
        public string CODI_CCO { get; set; }
        public string CODI_PRO_CORREDOR { get; set; }
        public string CODI_PRO_VENEDOR { get; set; }
        public string CODI_PRO_CARROCER { get; set; }
        public Nullable<System.DateTime> DATA_GARANTIA { get; set; }
        public decimal INT_SI_NO { get; set; }
        public string CODI_XOF_HAB { get; set; }
        public string CODI_AJU_HAB { get; set; }
        public string EMERGENCIES { get; set; }
        public decimal UMPC_SI_NO { get; set; }
        public decimal DRACO_SI_NO { get; set; }
        public string CODI_LOT_FCT { get; set; }
        public string ESTAT_VHI { get; set; }
        public decimal TIPUS_TERMINAL { get; set; }
        public string CODI_AER { get; set; }
        public string POTENCIA_FISCAL { get; set; }
        public string CILINDRADA { get; set; }
        public decimal TARA { get; set; }
        public Nullable<System.DateTime> DATA_FINAL_SRV { get; set; }
        public string VHI_EXTERN { get; set; }
        public string POLIZA { get; set; }
        public decimal SIRENA_SI_NO { get; set; }
        public decimal PANIC_SI_NO { get; set; }
        public string CODI_CHK { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public decimal LONGITUD { get; set; }
        public decimal LATITUD { get; set; }
        public decimal VELOCITAT { get; set; }
        public Nullable<System.DateTime> DATA_GPS { get; set; }
        public string CODI_SOCI_1 { get; set; }
        public string CODI_SOCI_2 { get; set; }
        public string CODI_SOCI_3 { get; set; }
        public string CODI_SOCI_4 { get; set; }
        public string CODI_SOCI_5 { get; set; }
        public decimal TANT_X100_SOCI_1 { get; set; }
        public decimal TANT_X100_SOCI_2 { get; set; }
        public decimal TANT_X100_SOCI_3 { get; set; }
        public decimal TANT_X100_SOCI_4 { get; set; }
        public decimal TANT_X100_SOCI_5 { get; set; }
        public int BATERIA { get; set; }
        public decimal ACTIVAR_VHI_SERGAS_SI_NO { get; set; }
        public decimal PRIORITAT_VHI_SERGAS { get; set; }
        public string E_MAIL_AVIS { get; set; }
        public string COLOR { get; set; }
        public string PLANTILLA { get; set; }
        public decimal RAMPA_SI_NO { get; set; }
        public decimal ELEVADOR_SI_NO { get; set; }
        public decimal CAMILLA_SI_NO { get; set; }
        public decimal ANCORES_CADIRA_RODES_SI_NO { get; set; }
        public string VERSIO_FIRM { get; set; }
        public string EMEI { get; set; }
        public string CODI_TRA_1 { get; set; }
        public string CODI_TRA_2 { get; set; }
        public string CODI_TRA_3 { get; set; }
        public string CODI_TRA_4 { get; set; }
        public string CODI_TRA_5 { get; set; }
        public string CODI_TRA_6 { get; set; }
        public decimal COST_PER_HORA { get; set; }
        public decimal COST_PER_KM { get; set; }
        public decimal COMBINA_SEIENT_1 { get; set; }
        public decimal COMBINA_SEIENT_2 { get; set; }
        public decimal COMBINA_SEIENT_3 { get; set; }
        public decimal COMBINA_SEIENT_4 { get; set; }
        public decimal COMBINA_SEIENT_5 { get; set; }
        public decimal COMBINA_SEIENT_6 { get; set; }
        public decimal COMBINA_CADIRA_1 { get; set; }
        public decimal COMBINA_CADIRA_2 { get; set; }
        public decimal COMBINA_CADIRA_3 { get; set; }
        public decimal COMBINA_CADIRA_4 { get; set; }
        public decimal COMBINA_CADIRA_5 { get; set; }
        public decimal COMBINA_CADIRA_6 { get; set; }
        public decimal COMBINA_CAMILLA_1 { get; set; }
        public decimal COMBINA_CAMILLA_2 { get; set; }
        public decimal COMBINA_CAMILLA_3 { get; set; }
        public decimal COMBINA_CAMILLA_4 { get; set; }
        public decimal COMBINA_CAMILLA_5 { get; set; }
        public decimal COMBINA_CAMILLA_6 { get; set; }
        public decimal COMBINA_SEIENTS_1 { get; set; }
        public Nullable<System.DateTime> DARRERA_DATA_GPS { get; set; }
        public decimal CAMILLA { get; set; }
        public decimal CAMILLA_MAXIM { get; set; }
        public decimal CAMILLA_SEIENTS_RESTA { get; set; }
        public decimal CADIRA_RODES { get; set; }
        public decimal CADIRA_RODES_MAXIM { get; set; }
        public decimal CADIRA_RODEs_SEIENTS_RESTA { get; set; }
        public decimal DARRERA_X { get; set; }
        public decimal DARRERA_Y { get; set; }
        public decimal HUELLA_SI_NO { get; set; }
        public decimal COMBINACIO_DEFECTE { get; set; }
        public string CODI_AGR { get; set; }
        public string CODI_RCU { get; set; }
        public Nullable<System.DateTime> DATA_DARRERA_VELOCITAT { get; set; }
        public string CODI_SCC { get; set; }
    }
}
