//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHI_CHK
    {
        public string CODI_VHI { get; set; }
        public string CODI_CHK { get; set; }
        public string SYS_215_CHK { get; set; }
        public string SYS_215_VHI_CHK { get; set; }
        public Nullable<System.DateTime> DATA_ALTA { get; set; }
        public Nullable<System.DateTime> DATA_REVISAT { get; set; }
        public Nullable<System.DateTime> DATA_OTR { get; set; }
        public string CODI_XOF { get; set; }
        public string CODI_AJU { get; set; }
        public decimal KM { get; set; }
        public string ESTAT_CHK { get; set; }
        public string TIPUS_RESPOSTA { get; set; }
        public string TEST_1 { get; set; }
        public string TEST_2 { get; set; }
        public string TEST_3 { get; set; }
        public string TEST_4 { get; set; }
        public string OBS_VHI { get; set; }
        public string OBS_TALLER { get; set; }
        public string OBS { get; set; }
        public string NUM_OTR { get; set; }
        public string CODI_MAT { get; set; }
        public decimal UNITATS_DEMANADES { get; set; }
        public decimal ORDRE { get; set; }
        public string TEST_1_SI_NO { get; set; }
        public string TEST_2_SI_NO { get; set; }
        public string TEST_3_SI_NO { get; set; }
        public string TEST_4_SI_NO { get; set; }
        public string PREGUNTA { get; set; }
        public string SERIE { get; set; }
        public string NUM_COC { get; set; }
        public Nullable<System.DateTime> DATA_COC { get; set; }
    }
}
