//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHI_SIN
    {
        public string SYS_215 { get; set; }
        public string CODI_VHI { get; set; }
        public string POLIZA { get; set; }
        public string DOM_SINISTRE { get; set; }
        public string POB_SINISTRE { get; set; }
        public string PRV_SINISTRE { get; set; }
        public string DES { get; set; }
        public string RESOLUCIO { get; set; }
        public decimal CULPA_NOSTRE_SI_NO { get; set; }
        public string CODI_XOF { get; set; }
        public string CODI_AJU { get; set; }
        public string MATRICULA_CONTRARIA { get; set; }
        public string CODI_LOT_CONTRARIA { get; set; }
        public string POLIZA_CONTRARIA { get; set; }
        public string VHI_CONTRARI { get; set; }
        public string TEL_CONTRARI { get; set; }
        public string DANYS_CONTRARI { get; set; }
        public decimal COST_REPARAR { get; set; }
        public string REFERENCIA { get; set; }
        public decimal XOF_LESIONAT_SI_NO { get; set; }
        public decimal AJU_LESIONAT_SI_NO { get; set; }
        public decimal PAC_LESIONAT_SI_NO { get; set; }
        public decimal PERITATGE_SI_NO { get; set; }
        public Nullable<System.DateTime> DATA_SINISTRE { get; set; }
        public Nullable<System.DateTime> DATA_PERITATGE { get; set; }
        public Nullable<System.DateTime> DATA_CANVI_ESTAT { get; set; }
        public string OBS { get; set; }
        public string ESTAT_SIN { get; set; }
    }
}
