//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHI_INC
    {
        public string SYS_215 { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<System.DateTime> DATA_MIS { get; set; }
        public string CODI_VHI { get; set; }
        public string CODI_INC { get; set; }
        public string CODI_USU { get; set; }
        public string CODI_XOF { get; set; }
        public string CODI_AJU { get; set; }
        public string ORIGEN_INC { get; set; }
        public string OBS { get; set; }
        public string ESTAT { get; set; }
    }
}
