//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHI_GPS
    {
        public int SYS_215 { get; set; }
        public string CODI_VHI { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string ACCIO { get; set; }
        public decimal X { get; set; }
        public decimal Y { get; set; }
        public decimal LATITUD { get; set; }
        public decimal LONGITUD { get; set; }
        public decimal VELOCITAT { get; set; }
    }
}
