//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIP
    {
        public string CODI_TRB { get; set; }
        public decimal ORDRE { get; set; }
        public string TIPUS_VIP { get; set; }
        public string OBS { get; set; }
        public string TEL { get; set; }
        public decimal INACTIU_SI_NO { get; set; }
        public decimal ASSIGNAT_SI_NO { get; set; }
        public string NOM { get; set; }
    }
}
