//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamIntraStandard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_HIS
    {
        public int SYS_215 { get; set; }
        public string CODI_USU { get; set; }
        public string ACCIO { get; set; }
        public string DADES { get; set; }
        public Nullable<System.DateTime> DATA_ALTA { get; set; }
        public Nullable<System.DateTime> DATA_PETICIO { get; set; }
        public string APP { get; set; }
        public string CODI_TRB_DESTI { get; set; }
    }
}
